### PR TITLE
LinkedDataHub upgrade

### PR DESCRIPTION
**Pull request by namedgraph**
Changes
* new routing model to allow sub-apps to have prefix URI instead of a base URI
* map not showing up should be fixed
* RDF download button fixed
* `?uri=` param is not used with local URIs anymore

### CODE REVIEW

**Comment by Piiit** [comment]
@namedgraph Thx

**Comment by Piiit** [comment]
@bcogrel Could you please deploy this new version? If everything works, we could start to migrate to our real staging and production servers and I could create a Jenkins pipeline... What do you think?

**Comment by bcogrel** [comment]
Sure. @jcte02, could you please give it a try?

**Comment by jcte02** [comment]
Deployed

**Pull request merged**
